HastaneRandevu/Models/Randevu.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace HastaneRandevu.Models
{
    public class Randevu
    {
        public int Id { get; set; }


        public int HastaId {  get; set; }
        [ForeignKey("HastaAdi")]
        public string HastaAdi {  get; set; }
        [ForeignKey("HastaSoyadi")]
        public string HastaSoyadi {  get; set; }

        public int DoktorId { get; set; }
        [ForeignKey("DoktorId")]
        public Doktor Doktor { get; set; }




    }
}

HastaneRandevu/Controllers/RandevuController.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using HastaneRandevu.Models;
using HastaneRandevu.Utility;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Authorization;

namespace HastaneRandevu.Controllers
{
    

    public class RandevuController : Controller
    {
        private readonly IDoktorRepository _doktorRepository;
        private readonly IRandevuRepository _randevuRepository;
        private readonly IWebHostEnvironment _webHostEnvironment;

        public RandevuController(IDoktorRepository doktorRepository, IRandevuRepository randevuRepository, IWebHostEnvironment webHostEnvironment)
        {
            _doktorRepository = doktorRepository;
            _randevuRepository = randevuRepository;
            _webHostEnvironment = webHostEnvironment;
        }
        public IActionResult Index()
        {
            List<Randevu> objRandevuList = _randevuRepository.GetAll(includeProps: "Doktor").ToList();
            return View(objRandevuList);
        }

        public IActionResult EkleGuncelle(int? id)
        {
            IEnumerable<SelectListItem> DoktorList = _doktorRepository.GetAll().Select(k => new SelectListItem
            {
                Text = $"{k.ad} {k.soyad}",
                Value = k.Id.ToString()
            });

            ViewBag.Doktor = DoktorList;

            if (id == null || id == 0)
            {
                // Ekle
                return View();
            }
            else
            {
                // Guncelle
                Randevu? randevuVt = _randevuRepository.Get(u => u.Id == id);
                if (randevuVt == null)
                {
                    return NotFound();
                }
                return View(randevuVt);
            }
        }
        [HttpPost]
        public IActionResult EkleGuncelle(Randevu randevu)
        {
            if (ModelState.IsValid)
            {
                if (randevu.Id == 0)
                {
                    _randevuRepository.Ekle(randevu);
                    TempData["basarili"] = "Yeni Randevu Basariyla Alindi";

                }
                else
                {
                    _randevuRepository.Guncelle(randevu);
                    TempData["basarili"] = "Randevu Basariyla Guncellendi";


                }
                _randevuRepository.Kaydet();
                return RedirectToAction("Index");
            }
            return View();
        }

        public IActionResult Sil(int? id)
        {
            IEnumerable<SelectListItem> DoktorList = _doktorRepository.GetAll().Select(k => new SelectListItem
            {
                Text = $"{k.ad} {k.soyad}",
                Value = k.Id.ToString()
            });
            ViewBag.Doktor = DoktorList;

            if (id == null || id == 0)
            {
                return NotFound();
            }
            Randevu? randevuVt = _randevuRepository.Get(u => u.Id == id);
            if (randevuVt == null)
            {
                return NotFound();
            }
            return View(randevuVt);
        }
        [HttpPost, ActionName("Sil")]
        public IActionResult SilPOST(int? id)
        {
            Randevu? randevu = _randevuRepository.Get(u => u.Id == id);
            if (randevu == null)
            {
                return NotFound();
            }
            _randevuRepository.Sil(randevu);
            _randevuRepository.Kaydet();
            TempData["basarili"] = "Randevu Basariyla Silindi";
            return RedirectToAction("Index");
        }
    }
}

HastaneRandevu/Views/Randevu/EkleGuncelle.cshtml
@model Randevu

<!-- randevu ekle güncelle -->
<form method="post">

    <div class="border p-3 mt-5">
        <div class="row pb-3">
            <h2 class="text-primary">@(Model == null? "Randevu Al" : "Randevu Guncelle")</h2>
            <hr>
        </div>
        <div class="mb-3">
            <label asp-for="HastaId" class="p-0">Hasta ID: </label>
            <input asp-for="HastaId" class="form-control" />
            <span asp-validation-for="HastaId" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <label asp-for="HastaAdi" class="p-0">Hasta Adi: </label>
            <input asp-for="HastaAdi" class="form-control" />
            <span asp-validation-for="HastaAdi" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <label asp-for="HastaSoyadi" class="p-0">Hasta Soyadi: </label>
            <input asp-for="HastaSoyadi" class="form-control" />
            <span asp-validation-for="HastaSoyadi" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <label asp-for="DoktorId" class="p-0">Doktor</label>
            <select asp-for="DoktorId" asp-items="ViewBag.Doktor" class="form-select"></select>
        </div>
        

        @if(Model != null)
        {
            <button type="submit" class="btn btn-lg btn-primary" style="width:200px">Randevu Guncelle</button>
        }
        else
        {
            <button type="submit" class="btn btn-lg btn-primary" style="width:200px">Randevu Al</button>

        }


        <a asp-controller="Randevu" asp-action="Index" class="btn btn-lg btn-info" style="width:200px">Geri Don</a>
    </div>

</form>

HastaneRandevu/Views/Randevu/Index.cshtml
@model List<Randevu>
@using HastaneRandevu.Utility


@if (TempData["basarili"] != null){
    <div class="row pt-3 pb-2">
    <h2>@TempData["basarili"]</h2>
    </div>
}
else{
    <div class="row pt-3 pb-2">
    <h2>Randevular</h2>
    </div>
}


<div class="row pt-3 pb-2" style="margin-left: 2px;">
    <table class="table table-light">
    <thead>
    <tr class="table-light">
        
        <th scope="col">
            Hasta No
        </th>
        <th scope="col">
            Hasta Adi
        </th>
        <th scope="col">
            Hasta Soyadi
        </th>
        <th scope="col">
            Doktor
        </th>
        <th scope="col">
            
        
        <th scope="col">
            
        </th>  

            </tr>
    </thead>

    <tbody>
        @foreach(var randevu in Model)
        { 
        <tr>
            <td>@randevu.HastaId</td>
            <td>@randevu.HastaAdi</td>
            <td>@randevu.HastaSoyadi</td>
            <td>@randevu.Doktor.ad @randevu.Doktor.soyad</td>
            @if (User.IsInRole(UserRoles.Role_User))
                {
                <td>
                    <a asp-controller="Randevu" asp-action="EkleGuncelle" asp-route-id="@randevu.Id" type="button" class="btn btn-outline-success" style="width:125px">Guncelle</a>
                </td>
                <td>
                    <a asp-controller="Randevu" asp-action="Sil" asp-route-id="@randevu.Id" type="button" class="btn btn-outline-danger" style="width:125px">Sil</a>
                </td>
                }
        </tr>
        }
    </tbody>
        
</table>
</div>

<div class="row pt-3 pb-2">
    <div>
        <a asp-controller="Randevu" asp-action="EkleGuncelle" class="btn btn-lg btn-primary" type="button">
            Yeni Randevu Al
        </a>
    </div>
</div>

HastaneRandevu/Views/Randevu/Sil.cshtml
@model Randevu

<form method="post">

    <div class="border p-3 mt-5">
        <div class="row pb-3">
            <h2 class="text-primary">Randevu Iptal</h2>
            <hr>
        </div>
        <div class="mb-3">
            <label asp-for="HastaId" class="p-0">Doktorun Adi: </label>
            <input asp-for="HastaId" disabled class="form-control" />
        </div>      
        <div class="mb-3">
            <label asp-for="DoktorId" class="p-0">Doktor</label>
            <select asp-for="DoktorId" asp-items="ViewBag.Doktor" disabled class="form-select"></select>
        </div>
        <button type="submit" class="btn btn-lg btn-secondary" style="width:200px">Randevu Iptal</button>

        <a asp-controller="Randevu" asp-action="Index" class="btn btn-lg btn-info" style="width:200px">Geri Don</a>
    </div>

</form>