HastaneRandevu/Models/Doktor.cs
using Microsoft.AspNetCore.Mvc.ModelBinding.Validation;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace HastaneRandevu.Models
{
    public class Doktor
    {
        [Key] //primary key
        public int Id { get; set; }

        [Required(ErrorMessage = "Lutfen gecerli bir AD giriniz.")]
        [MaxLength(25)]
        public string ad { get; set; }

        [Required(ErrorMessage = "Lutfen gecerli bir SOYAD giriniz.")]
        [MaxLength(30)]
        public string soyad { get; set; }

        [ValidateNever]
        public int BolumId { get; set; }
        [ValidateNever]
        [ForeignKey("BolumId")]
        public Bolum? Bolum { get; set;}

    
    }
}

HastaneRandevu/Controllers/DoktorController.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using HastaneRandevu.Models;
using HastaneRandevu.Utility;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Authorization;

namespace HastaneRandevu.Controllers
{
    //doktor kontroller
    public class DoktorController : Controller
    {
        private readonly IDoktorRepository _doktorRepository;
        private readonly IBolumRepository _bolumRepository;
        private readonly IWebHostEnvironment _webHostEnvironment;

        public DoktorController(IDoktorRepository doktorRepository, IBolumRepository bolumRepository, IWebHostEnvironment webHostEnvironment)
        {
            _doktorRepository = doktorRepository;
            _bolumRepository = bolumRepository;
            _webHostEnvironment = webHostEnvironment;
        }
        public IActionResult Index()
        {
            // List<Doktor> objDoktorList = _doktorRepository.GetAll().ToList()
            List<Doktor> objDoktorList = _doktorRepository.GetAll(includeProps:"Bolum").ToList();
            return View(objDoktorList);
        }

        [Authorize(Roles = UserRoles.Role_Admin)]

        public IActionResult EkleGuncelle(int? id)
        {
            IEnumerable<SelectListItem> BolumList = _bolumRepository.GetAll().Select(k => new SelectListItem
            {
                Text = k.bolumAdi,
                Value = k.Id.ToString()
            });

            ViewBag.Bolum = BolumList;

            if(id == null || id == 0)
            {
                // Ekle
                return View();
            }
            else
            {
                // Guncelle
                Doktor? doktorVt = _doktorRepository.Get(u => u.Id == id);
                if (doktorVt == null)
                {
                    return NotFound();
                }
                return View(doktorVt);
            }
        }

        [Authorize(Roles = UserRoles.Role_Admin)]
        [HttpPost]
        public IActionResult EkleGuncelle(Doktor dt)
        {
            if (ModelState.IsValid)
            {
                if(dt.Id == 0)
                {
                    _doktorRepository.Ekle(dt);
                    TempData["basarili"] = "Yeni Doktor Basariyla Eklendi";

                }
                else
                {
                    _doktorRepository.Guncelle(dt);
                    TempData["basarili"] = "Doktor Basariyla Guncellendi";


                }
                _doktorRepository.Kaydet();
                return RedirectToAction("Index");
            }
            return View();
        }

        [Authorize(Roles = UserRoles.Role_Admin)]
        public IActionResult Sil(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            Doktor? doktorVt = _doktorRepository.Get(u => u.Id == id);
            if (doktorVt == null)
            {
                return NotFound();
            }
            return View(doktorVt);
        }
        [Authorize(Roles = UserRoles.Role_Admin)]
        [HttpPost, ActionName("Sil")]
        public IActionResult SilPOST(int? id)
        {
            Doktor? dt = _doktorRepository.Get(u => u.Id == id);
            if(dt == null)
            {
                return NotFound();
            }
            _doktorRepository.Sil(dt);
            _doktorRepository.Kaydet();
            TempData["basarili"] = "Doktor Basariyla Silindi";
            return RedirectToAction("Index");
        }
    }
}

HastaneRandevu/Views/Doktor/DoktorEkle.cshtml
@model Doktor

<form method="post">

    <div class="border p-3 mt-5">
        <div class="row pb-3">
            <h2 class="text-primary">Doktor Ekle</h2>
            </hr>
        </div>

        <div class="mb-3">
            <label asp-for="ad" class="p-0">Doktorun Adi: </label>
            <input asp-for="ad" class="form-control" />
            <span asp-validation-for="ad" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <label asp-for="soyad" class="p-0">Doktorun Soyadi: </label>
            <input asp-for="soyad" class="form-control" />
            <span asp-validation-for="soyad" class="text-danger"></span>

        </div>
        <div class="mb-3">
            <label asp-for="uzmanlik" class="p-0">Doktorun Uzmanligi: </label>
            <input asp-for="uzmanlik" class="form-control" />
            <span asp-validation-for="uzmanlik" class="text-danger"></span>

        </div>
        <div class="mb-3">
            <label asp-for="vardiya" class="p-0">Doktorun Vardiyasi: </label>
            <input asp-for="vardiya" class="form-control" />
            <span asp-validation-for="vardiya" class="text-danger"></span>

        </div>


        <button type="submit" class="btn btn-lg btn-primary" style="width:200px">Doktor Ekle</button>

        <a asp-controller="Doktor" asp-action="Index" class="btn btn-lg btn-info" style="width:200px">Geri Don</a>
    </div>

</form>

HastaneRandevu/Views/Doktor/EkleGuncelle.cshtml
@model Doktor
@using HastaneRandevu.Utility

<form method="post">
    <!-- ekle güncelle. -->
    <div class="border p-3 mt-5">
        <div class="row pb-3">
            <h2 class="text-primary">@(Model == null? "Doktor Ekle" : "Doktor Guncelle")</h2>
        </div>
        <div class="mb-3">
            <label asp-for="ad" class="p-0">Doktorun Adi: </label>
            <input asp-for="ad" class="form-control" />
            <span asp-validation-for="ad" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <label asp-for="soyad" class="p-0">Doktorun Soyadi: </label>
            <input asp-for="soyad" class="form-control" />
            <span asp-validation-for="soyad" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <label asp-for="BolumId" class="p-0">Bolum</label>
            <select asp-for="BolumId" asp-items="ViewBag.Bolum" class="form-select" ></select>
            <span asp-validation-for="BolumId" class="text-danger"></span>
        </div>
        

        @if(Model != null)
        {
            <button type="submit" class="btn btn-lg btn-primary" style="width:200px">Doktor Guncelle</button>
        }
        else
        {    
            <button type="submit" class="btn btn-lg btn-primary" style="width:200px">Doktor Ekle</button>           
        }


        <a asp-controller="Doktor" asp-action="Index" class="btn btn-lg btn-info" style="width:200px">Geri Don</a>
    </div>

</form>

HastaneRandevu/Views/Doktor/Guncelle.cshtml
@model Doktor

<form method="post">

    <div class="border p-3 mt-5">
        <div class="row pb-3">
            <h2 class="text-primary">Doktor Guncelle</h2>
            </hr>
        </div>

        <div class="mb-3">
            <label asp-for="ad" class="p-0">Doktorun Adi: </label>
            <input asp-for="ad" class="form-control" />
            <span asp-validation-for="ad" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <label asp-for="soyad" class="p-0">Doktorun Soyadi: </label>
            <input asp-for="soyad" class="form-control" />
            <span asp-validation-for="soyad" class="text-danger"></span>
         <div class="mb-3">
            <label asp-for="BolumId" class="p-0">Bolum</label>
            <select asp-for="BolumId" asp-items="ViewBag.Bolum" class="form-select" ></select>
            <span asp-validation-for="BolumId" class="text-danger"></span>
        </div>

        </div>
        
        <button type="submit" class="btn btn-lg btn-primary" style="width:200px">Doktor Guncelle</button>

        <a asp-controller="Doktor" asp-action="Index" class="btn btn-lg btn-info" style="width:200px">Geri Don</a>
    </div>

</form>

HastaneRandevu/Views/Doktor/Index.cshtml
@model List<Doktor>
@using HastaneRandevu.Utility

@if (TempData["basarili"] != null){
    <div class="row pt-3 pb-2">
    <h2>@TempData["basarili"]</h2>
    </div>
}
else{
    <div class="row pt-3 pb-2">
    <h2>Doktorlar</h2>
    </div>
}


<div class="row pt-3 pb-2" style="margin-left: 2px;">
    <table class="table table-light">
    <thead>
    <tr class="table-light">
        <th scope="col">
            Bolum
        </th>
        <th scope="col">
            Doktor Adi
        </th>
        
    </tr>
    </thead>
    <tbody>
        @foreach(var doktor in Model)
        {
        <tr>
            <td> @doktor.Bolum.bolumAdi</td>
            <td> @doktor.ad @doktor.soyad </td>
            @if (User.IsInRole(UserRoles.Role_Admin))
            {
                <td>
                <a asp-controller="Doktor" asp-action="EkleGuncelle" asp-route-id="@doktor.Id" type="button" class="btn btn-outline-success" style="width:125px">Guncelle</a>
                </td>
            }
            @if (User.IsInRole(UserRoles.Role_Admin))
            {
                <td>
                <a asp-controller="Doktor" asp-action="Sil" asp-route-id="@doktor.Id" type="button" class="btn btn-outline-danger" style="width:125px">Sil</a>
                </td>
            }
        </tr>
        }
    </tbody>
        
</table>
</div>

<div class="row pt-3 pb-2">
    @if (User.IsInRole(UserRoles.Role_Admin))
    {
        <div>
            <a asp-controller="Doktor" asp-action="EkleGuncelle" class="btn btn-lg btn-primary" type="button">
                Doktor Ekle
            </a>
        </div>
    }
    
</div>

HastaneRandevu/Views/Doktor/Sil.cshtml
@model Doktor

<form method="post">

    <div class="border p-3 mt-5">
        <div class="row pb-3">
            <h2 class="text-primary">Doktor Sil</h2>
            </hr>
        </div>

        <div class="mb-3">
            <label asp-for="ad" class="p-0">Doktorun Adi: </label>
            <input asp-for="ad" disabled class="form-control" />
            <span asp-validation-for="ad" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <label asp-for="soyad" class="p-0">Doktorun Soyadi: </label>
            <input asp-for="soyad" disabled class="form-control" />
            <span asp-validation-for="soyad" class="text-danger"></span>

        </div>
       
        <button type="submit" class="btn btn-lg btn-secondary" style="width:200px">Doktor Sil</button>

        <a asp-controller="Doktor" asp-action="Index" class="btn btn-lg btn-info" style="width:200px">Geri Don</a>
    </div>

</form>