HastaneRandevu/Models/Bolum.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace HastaneRandevu.Models
{
    public class Bolum
    {
        [Key] public int Id { get; set; }

        [Required(ErrorMessage = "Lutfen gecerli bir BOLUM giriniz.")]
        public string bolumAdi { get; set; }



    }
}

HastaneRandevu/Controllers/BolumController.cs
using HastaneRandevu.Models;
using HastaneRandevu.Utility;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace HastaneRandevu.Controllers
{
    public class BolumController : Controller
    {
        private readonly IBolumRepository _bolumRepository;
        public BolumController(IBolumRepository context)
        {
            _bolumRepository = context;
        }
        public IActionResult Index()
        {
            List<Bolum> objBolumList = _bolumRepository.GetAll().ToList();
            return View(objBolumList);
        }

        [Authorize(Roles = UserRoles.Role_Admin)]
        public IActionResult Ekle()
        {
            return View();
        }

        [Authorize(Roles = UserRoles.Role_Admin)]
        [HttpPost]
        public IActionResult Ekle(Bolum bl)
        {
            if (ModelState.IsValid)
            {
                _bolumRepository.Ekle(bl);
                _bolumRepository.Kaydet();
                TempData["basarili"] = "Yeni Bolum Basariyla Eklendi";
                return RedirectToAction("Index");
            }
            return View();
        }

        //userroles
        [Authorize(Roles = UserRoles.Role_Admin)]
        public IActionResult Guncelle(int? id)
        {
            if(id== null || id==0)
            {
                return NotFound();
            }
            Bolum? bolumVt = _bolumRepository.Get(u=>u.Id==id);
            if(bolumVt == null)
            {
                return NotFound();
            }
            return View(bolumVt);
        }

        [Authorize(Roles = UserRoles.Role_Admin)]
        [HttpPost]
        public IActionResult Guncelle(Bolum bl)
        {
            if (ModelState.IsValid)
            {
                _bolumRepository.Guncelle(bl);
                _bolumRepository.Kaydet();
                TempData["basarili"] = "Bolum Basariyla Guncellendi";
                return RedirectToAction("Index");
            }
            return View();
        }

        [Authorize(Roles = UserRoles.Role_Admin)]
        public IActionResult Sil(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            Bolum? bolumVt = _bolumRepository.Get(u => u.Id == id);
            if (bolumVt == null)
            {
                return NotFound();
            }
            return View(bolumVt);
        }

        [Authorize(Roles = UserRoles.Role_Admin)]
        [HttpPost, ActionName("Sil")]
        public IActionResult SilPOST(int? id)
        {
            Bolum? bl = _bolumRepository.Get(u => u.Id == id);
            if(bl == null)
            {
                return NotFound();
            }
            _bolumRepository.Sil(bl);
            _bolumRepository.Kaydet();
            TempData["basarili"] = "Bolum Basariyla Silindi";
            return RedirectToAction("Index");
        }
    }
}

HastaneRandevu/Views/Bolum/Ekle.cshtml
@model Bolum

<form method="post">

    <div class="border p-3 mt-5">
        <div class="row pb-3">
            <h2 class="text-primary">Bolum Ekle</h2>
            </hr>
        </div>

        <div class="mb-3">
            <label asp-for="bolumAdi" class="p-0">Bolumun Adi: </label>
            <input asp-for="bolumAdi" class="form-control" />
            <span asp-validation-for="bolumAdi" class="text-danger"></span>
        </div>        
        <button type="submit" class="btn btn-lg btn-primary" style="width:200px">Bolum Ekle</button>

        <a asp-controller="Bolum" asp-action="Index" class="btn btn-lg btn-info" style="width:200px">Geri Don</a>
    </div>

</form>

HastaneRandevu/Views/Bolum/Guncelle.cshtml
@model Bolum

<form method="post">

    <div class="border p-3 mt-5">
        <div class="row pb-3">
            <h2 class="text-primary">Bolum Guncelle</h2>
            </hr>
        </div>

        <div class="mb-3">
            <label asp-for="bolumAdi" class="p-0">Bolumun Adi: </label>
            <input asp-for="bolumAdi" class="form-control" />
            <span asp-validation-for="bolumAdi" class="text-danger"></span>
        </div>       
        <button type="submit" class="btn btn-lg btn-primary" style="width:200px">Bolum Guncelle</button>

        <a asp-controller="Bolum" asp-action="Index" class="btn btn-lg btn-info" style="width:200px">Geri Don</a>
    </div>

</form>

HastaneRandevu/Views/Bolum/Index.cshtml
@model List<Bolum>
@using HastaneRandevu.Utility


@if (TempData["basarili"] != null){
    <div class="row pt-3 pb-2">
    <h2 color:blue" >@TempData["basarili"]</h2>
    </div>
}
else{
    <div class="row pt-3 pb-2">
    <h2>Bolumler</h2>
    </div>
}
<div class="row pt-3 pb-2" style="margin-left: 2px;">
<table class="table table-light">
    <thead>
    <tr>     
        <th scope="col">
            Bolum Adi
        </th>           
        @if (User.IsInRole(UserRoles.Role_Admin))
        {
            <th scope="col">

            </th>
            <th scope="col">

            </th>
        }
    </tr>
    </thead>
    <tbody>
        @foreach(var bolum in Model)
        {
        <tr>
            <td> @bolum.bolumAdi </td>
            @if(User.IsInRole(UserRoles.Role_Admin)){
                <td>
                    <a asp-controller="Bolum" asp-action="Guncelle" asp-route-id="@bolum.Id" type="button" class="btn btn-outline-success" style="width:125px">Guncelle</a>
                </td>
                <td>
                    <a asp-controller="Bolum" asp-action="Sil" asp-route-id="@bolum.Id" type="button" class="btn btn-outline-danger" style="width:125px">Sil</a>
                </td>
            }
        </tr>
        }
    </tbody>
        
</table>
</div>

<div class="row pt-3 pb-2">
    @if (User.IsInRole(UserRoles.Role_Admin))
    {
        <div>
            <a asp-controller="Bolum" asp-action="Ekle" class="btn btn-lg btn-primary" type="button">
                Bolum Ekle
            </a>
        </div>
    }
</div>

HastaneRandevu/Views/Bolum/Sil.cshtml
@model Bolum

<form method="post">

    <div class="border p-3 mt-5">
        <div class="row pb-3">
            <h2 class="text-primary">Bolum Sil</h2>
            </hr>
        </div>

        <div class="mb-3">
            <label asp-for="bolumAdi" class="p-0">Bolumun Adi: </label>
            <input asp-for="bolumAdi" disabled class="form-control" />
            <span asp-validation-for="bolumAdi" class="text-danger"></span>
        </div>
        <button type="submit" class="btn btn-lg btn-secondary" style="width:200px">Bolum Sil</button>

        <a asp-controller="Bolum" asp-action="Index" class="btn btn-lg btn-info" style="width:200px">Geri Don</a>
    </div>

</form>